"""empty message

Revision ID: d2e43dd012ec
Revises: ab23f80b44c2
Create Date: 2020-11-27 02:00:15.395187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e43dd012ec'
down_revision = 'ab23f80b44c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'goal_id')
    # ### end Alembic commands ###
